from __future__ import annotations

from datetime import datetime
from typing import Any, Callable, Dict, List, Optional, Protocol, runtime_checkable


# ── Repository Interfaces ─────────────────────────────────────────


@runtime_checkable
class IPageRepository(Protocol):
    def save_pages(self, token: str, pages: List[Dict[str, Any]]) -> None: ...
    def load_cached_pages(self, token: str) -> List[Dict[str, Any]]: ...
    def load_all_cached_pages(self) -> List[Dict[str, Any]]: ...
    def delete_pages_for_token(self, token: str) -> None: ...


@runtime_checkable
class ITokenRepository(Protocol):
    def save_token_state(self, token: str, is_valid: bool, expires_at: Optional[str], error: Optional[str]) -> None: ...
    def save_account_state(self, token: str, is_valid: bool, expires_at: Optional[str], error: Optional[str], account_id: Optional[str] = None, account_name: Optional[str] = None, page_count: int = 0) -> None: ...
    def load_all_accounts(self) -> List[Dict[str, Any]]: ...


@runtime_checkable
class IPostRepository(Protocol):
    def log_successful_post(self, page_name: str, content: str, post_type: str) -> None: ...
    def load_recent_posts(self, offset: int, limit: int) -> tuple: ...
    def clear_recent_posts(self) -> None: ...
    def record_page_video(self, page_key: str, page_name: str, video_path: str, post_id: str = "", permalink_url: str = "") -> None: ...
    def load_successful_video_paths_for_page(self, page_key: str) -> set: ...
    def load_posted_video_names_for_page(self, page_key: str) -> set: ...
    def load_video_history(self, page_keys: Optional[List[str]] = None) -> List[Dict[str, Any]]: ...


@runtime_checkable
class IPageDetailRepository(Protocol):
    def save_page_details(self, page_id: str, details: Dict[str, Any]) -> None: ...
    def load_latest_page_detail(self, page_id: str) -> Optional[Dict[str, Any]]: ...
    def load_page_details_history(self, page_id: str, limit: int = 10) -> List[Dict[str, Any]]: ...


@runtime_checkable
class IConfigRepository(Protocol):
    def load(self) -> Dict[str, Any]: ...
    def save(self, payload: Dict[str, Any]) -> None: ...


@runtime_checkable
class IMediaRotationRepository(Protocol):
    def load_rotation_index(self, rotation_key: str) -> int: ...
    def save_rotation_index(self, rotation_key: str, next_video_index: int, last_item_path: str = "") -> None: ...


# ── External Client Interfaces ────────────────────────────────────


@runtime_checkable
class IFacebookGraphClient(Protocol):
    def get(self, endpoint: str, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...
    def post(self, endpoint: str, data: Optional[Dict[str, Any]] = None, files: Optional[Dict[str, Any]] = None) -> Dict[str, Any]: ...


@runtime_checkable
class IPageDetailFetcher(Protocol):
    def fetch_all(self, page_id: str, page_name: str, access_token: str) -> Dict[str, Any]: ...


@runtime_checkable
class IReelsUploader(Protocol):
    def start_upload(self, page: Dict, media_path: str, message: str, *, title: str = "", description: str = "", proxy_config: Optional[Dict] = None) -> Dict[str, Any]: ...
    def upload_binary(self, page: Dict, upload_id: str, media_path: str, *, proxy_config: Optional[Dict] = None) -> Dict[str, Any]: ...
    def finish_publish(self, page: Dict, upload_id: str, *, message: str = "", title: str = "", description: str = "", proxy_config: Optional[Dict] = None) -> Dict[str, Any]: ...
    def verify_public_visibility(self, page: Dict, upload_id: str, *, timeout_seconds: int = 120, proxy_config: Optional[Dict] = None) -> Dict[str, Any]: ...
    def get_permalink(self, page: Dict, upload_id: str, *, proxy_config: Optional[Dict] = None) -> Optional[str]: ...


@runtime_checkable
class IProxyProvider(Protocol):
    def fetch_proxy(self) -> Optional[Dict[str, Any]]: ...
    def release_proxy(self, proxy_data: Optional[Dict[str, Any]]) -> None: ...
    def build_proxy_config(self, proxy_data: Optional[Dict[str, Any]]) -> Optional[Dict[str, str]]: ...


@runtime_checkable
class ILicenseManager(Protocol):
    def validate_code(self, code: str) -> Optional[datetime]: ...
    def activate(self, code: str, expires_at: datetime) -> None: ...
    def is_active(self) -> bool: ...
    def is_permanent(self) -> bool: ...
    def remaining_label(self) -> str: ...
    def clear(self) -> None: ...
    def load_state(self) -> None: ...
    @property
    def code(self) -> Optional[str]: ...
    @property
    def expires_at(self) -> Optional[datetime]: ...


# ── View Interfaces (MVP) ────────────────────────────────────────


@runtime_checkable
class IMainView(Protocol):
    def show_status(self, text: str) -> None: ...
    def show_error(self, title: str, message: str) -> None: ...
    def show_info(self, title: str, message: str) -> None: ...
    def show_warning(self, title: str, message: str) -> None: ...
    def confirm(self, title: str, message: str) -> bool: ...
    def set_controls_enabled(self, enabled: bool) -> None: ...
    def update_trial_status(self, label: str, style: str) -> None: ...
    def get_token_input(self) -> str: ...
    def set_token_input(self, text: str) -> None: ...
    def log(self, message: str, level: str = "info") -> None: ...


@runtime_checkable
class IPageListView(Protocol):
    def populate_page_table(self, pages: List[Dict[str, Any]]) -> None: ...
    def update_pagination(self, current: int, total: int) -> None: ...
    def update_selection_summary(self, selected: int, total: int) -> None: ...
    def update_page_info(self, page_id: str, info: Dict[str, Any]) -> None: ...
    def set_page_post_status(self, page_id: str, status: str) -> None: ...


@runtime_checkable
class IConfigView(Protocol):
    def clear_config_table(self) -> None: ...
    def add_config_row(self, row_data: Dict[str, Any]) -> None: ...
    def find_config_row(self, page_name: str) -> int: ...
    def update_config_row(self, row_idx: int, row_data: Dict[str, Any]) -> None: ...
    def update_config_status(self, page_name: str, status: str, page_id: str = "") -> None: ...
    def update_config_link(self, page_name: str, link: str) -> None: ...
    def get_config_rows(self) -> List[Dict[str, str]]: ...
    def set_post_config_button_enabled(self, enabled: bool) -> None: ...
    def set_post_config_button_text(self, text: str) -> None: ...


@runtime_checkable
class IPageDetailView(Protocol):
    def populate_info(self, data: Dict[str, Any]) -> None: ...
    def populate_overview(self, stats: Dict[str, Any]) -> None: ...
    def populate_videos(self, videos: List[Dict[str, Any]]) -> None: ...
    def show_overlay(self, text: str) -> None: ...
    def hide_overlay(self) -> None: ...
    def show_success(self, message: str) -> None: ...
    def show_error(self, message: str) -> None: ...
    def set_refresh_enabled(self, enabled: bool) -> None: ...
    def set_refresh_text(self, text: str) -> None: ...
    def set_videos_loading(self, loading: bool) -> None: ...
    def set_stats_loading(self, loading: bool) -> None: ...


@runtime_checkable
class ISettingsView(Protocol):
    def get_proxy_config(self) -> Dict[str, Any]: ...
    def get_concurrency_config(self) -> Dict[str, Any]: ...
    def load_proxy_config(self, data: Dict[str, Any]) -> None: ...
    def load_concurrency_config(self, data: Dict[str, Any]) -> None: ...
